App.UserProfileView = Em.View.extend
  templateName: 'user_profile'
  profileImageUrl: 'http://a0.twimg.com/profile_images/1371183258/gravatar_reasonably_small.jpeg'
  fullName: 'Gregory Moeck'
  userName: 'gregmoeck'
  location: 'San Francisco, CA'
  bio: 'My bio'
  tweetCount: '100'
  followingCount: '200'
  followersCount: '300'
